name: Build GAMMAGLYPH

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  android:
    name: Build Android
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install dependencies
        run: npm install

      - name: Add Android platform
        run: cordova platform add android

      - name: Build Android APK
        run: cordova build android --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GAMMAGLYPH-Android
          path: |
            platforms/android/**/*.apk


  ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Add iOS platform
        run: cordova platform add ios

      - name: Build iOS
        run: cordova build ios --release --no-sign

      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: GAMMAGLYPH-iOS
          path: platforms/ios/build/**/*.app